### ISSUE TITLE
Revamp Menu

### ISSUE THREAD

**Issue by mcdenhoed** [johnthagen/rust-belt#133]
I think it would be a good idea to revamp the menu. Two things I'm thinking of:

* Put in the logo. Would give us a way to get our feet wet on the sprite library.
* I think it would be cool to have asteroids spawn like in the game, but collide with each other.

**Comment by johnthagen** [comment]
I like it. Can you sketch out a minimal POC?

**Comment by mcdenhoed** [comment]
Hey @johnthagen check out the menu_revamp branch. Pushed a fading-in title.

**Comment by johnthagen** [comment]
@mcdenhoed Nice! I like using the logo in the menu.

For me (on Windows 10), there is a pause and flicker before the fade in starts. Do you see that?

When we land this, we'll also want to move the logo into the `assets` folder, since the logo would then be a proper asset.

I sort of liked the menu options being left justified with the title (seemed to look a little more professional), so maybe we should also shift the logo to the right or shift the menu options to the left.

**Comment by johnthagen** [comment]
On second thought, not sure about justifying the menu options.

**Comment by mcdenhoed** [comment]
I don't see the pause and flicker personally, but I'm guessing that's happening because I fade out and then in. I just pushed a change that sets the initial opacity instead of fading out.

**Comment by johnthagen** [comment]
Closed in #152
