### ISSUE TITLE
Asteroids can possibly never make it into the screen

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#92]
I think it's possible for an `Asteroid` to never make it onto the screen if it spawns in a corner and never gets its radius fully into the screen.

Then I think it enters a black hole where it's flying around taking up resources but can't be shot.

**Comment by mcdenhoed** [comment]
Looks like there was a small logic error in my asteroid generation code. I was properly setting up the lower-bound of where asteroids could target to ensure they end up in the window, but I wasn't doing it properly for the upper bound. 

In certain cases, usually near a corner, it was possible for an asteroid to come on-screen and pass through its target point without ever getting enough on-screen to trip the "on-screen" flag, causing the asteroid to drift through once and then disappear forever. 

By making sure that the target bounds are within RADIUS_MAX pixels of the edge, we ensure (if not totally, 99.999% of the time) that every asteroid will, in drifting towards its target, come fully on screen at some point, and never exhibit the "one-and-done" behavior of this bug.

Fixed in #94

**Comment by johnthagen** [comment]
Fixed in #94
